spring:
  application:
    name: labwork
  jpa:
    hibernate:
      ddlAuto: none
    showSql: false
    properties:
      hibernate:
        format_sql: false
  mvc:
    servlet:
      path: /api/v1
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
server:
  port: ${PORT:8080}
jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER:Armemius}
  token-expiration: ${JWT_EXPIRATION_MS:900000}
springdoc:
  swagger-ui:
    path: /docs/
    enabled: true
  api-docs:
    path: /docs/schema
  packagesToScan: com.armemius.labwork
  pathsToMatch: /**
