CREATE TABLE coordinates
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    x  FLOAT                                   NOT NULL CHECK (x > -469),
    y  BIGINT                                  NOT NULL CHECK (y > -440),
    CONSTRAINT pk_coordinates PRIMARY KEY (id)
);

CREATE TABLE location
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    x  INTEGER                                 NOT NULL,
    y  FLOAT                                   NOT NULL,
    z  DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_location PRIMARY KEY (id)
);

CREATE TABLE address
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street   VARCHAR(255)                            NOT NULL,
    zip_code VARCHAR(24),
    town_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_address PRIMARY KEY (id),
    CONSTRAINT FK_ADDRESS_ON_TOWN FOREIGN KEY (town_id) REFERENCES location (id) ON DELETE CASCADE
);

CREATE TABLE organization
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    name                VARCHAR(255)                              NOT NULL,
    coordinates_id      BIGINT                                    NOT NULL,
    creation_date       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    official_address_id BIGINT,
    annual_turnover     FLOAT                                     NOT NULL CHECK (annual_turnover > 0),
    employees_count     INTEGER                                   NOT NULL CHECK (employees_count > 0),
    rating              FLOAT                                     NOT NULL CHECK (rating > 0),
    type                VARCHAR(255),
    postal_address_id   BIGINT,
    CONSTRAINT pk_organization PRIMARY KEY (id),
    CONSTRAINT FK_ORGANIZATION_ON_COORDINATES FOREIGN KEY (coordinates_id) REFERENCES coordinates (id) ON DELETE CASCADE,
    CONSTRAINT FK_ORGANIZATION_ON_OFFICIAL_ADDRESS FOREIGN KEY (official_address_id) REFERENCES address (id) ON DELETE CASCADE,
    CONSTRAINT FK_ORGANIZATION_ON_POSTAL_ADDRESS FOREIGN KEY (postal_address_id) REFERENCES address (id) ON DELETE CASCADE
);
