CREATE TABLE app_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(16)                             NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    role     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT uq_app_user_username UNIQUE (username)
);

ALTER TABLE address
    ADD owner_id BIGINT;

ALTER TABLE coordinates
    ADD owner_id BIGINT;

ALTER TABLE location
    ADD owner_id BIGINT;

ALTER TABLE organization
    ADD owner_id BIGINT;

ALTER TABLE address
    ADD CONSTRAINT FK_ADDRESS_ON_USER FOREIGN KEY (owner_id) REFERENCES app_user (id);

ALTER TABLE coordinates
    ADD CONSTRAINT FK_COORDINATES_ON_USER FOREIGN KEY (owner_id) REFERENCES app_user (id);

ALTER TABLE location
    ADD CONSTRAINT FK_LOCATION_ON_USER FOREIGN KEY (owner_id) REFERENCES app_user (id);

ALTER TABLE organization
    ADD CONSTRAINT FK_ORGANIZATION_ON_USER FOREIGN KEY (owner_id) REFERENCES app_user (id);